on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  update:
    name: ♻️ Update manifests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@master
      - name: ♻️ Run autoupdate
        uses: foosel/scoop-checkver-action@main
        with:
          bucket: bucket
          force: ${{ github.event.inputs.force }}
      - name: 🚀 Deploy changes
        run: |
          # set git author
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # create individual commit per updated manifest
          while read file; do
            if [[ $file == bucket/* ]] && [[ $file == *.json ]]; then
              version=$(cat $file | jq -r .version)
              manifest=$(basename $file .json)
              message="$manifest: Update to version $version"
              git add "$file"
              git commit -m "$message"
            fi
          done < <(git diff --name-only)

          # finally push
          git push
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
